apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: # <TRACKER-NAME> Example: jgroups-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: # <APP-NAME> Example: jgroups-tracker
    spec:
      containers:
      - name: # <CONTAINER-NAME> Example: jgroups-tracker
        image: # <IMAGE-NAME> Example: jocelynthode/jgroups-tracker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: # <PORT NUMBER> Example: 12001
