real_churn: # Database must be in sqlite3 format
  database: "databases/database.db"
  epoch: 0 # in seconds
  start_time: 10
  duration: 7200
  time_factor: 2 # Time multiplicator for the real churn
synthetic:
  # First tuple must always specify the starting size
  - !!python/tuple [0,26]
  - !!python/tuple [1,0]
  - !!python/tuple [1,0]
  - !!python/tuple [1,0]
  - !!python/tuple [1,1]
  - !!python/tuple [0,1]
